### PR TITLE
Neo Blue-eyes fix

### PR DESCRIPTION
**Pull request by LordOfNightmares**

### CODE REVIEW

**Comment by jacmaz** [comment]
The new Neo Blue-eyes Looks squashed do not you think?

**Comment by LordOfNightmares** [comment]
@jacmaz  i know but antimeta man told me to make it smaller to not occupy 2.5 space out of 3 fields

**Comment by shadowfox87** [comment]
I think now that I think about it, if people are playing ygopro 2, then they want these kinds of pics. If they don't they can turn off closeups. So I'll take the original pic that doesn't run the aspect ratio.

**Comment by LordOfNightmares** [comment]
yay :dancer:

**Pull request closed without merging**
